### ISSUE TITLE
Action '...' not defined

### ISSUE THREAD

**Issue by wottpal** [sebsel/queue-for-kirby#3]
Hey @sebsel,
I am trying to use your queue for the following: Whenever a comment (using the [Kirby Comments plugin](https://github.com/Addpixel/KirbyComments)) on my page is created a hook is fired and I want to commit & push my changes to my remote repository (using the [Git-Commit-And-Push-Content plugin](https://github.com/blankogmbh/kirby-git-commit-and-push-content)). But this significantly slows down the first page-load after the comment was created so I decided to try it asynchronously with your queue. 

I created a file under `site/plugins` which contains the following:

```php
kirby()->plugin('queue-for-kirby');
$queue_exists = class_exists('queue');
$should_commit = c::get('gcapc-commit', false);
$should_push = c::get('gcapc-push', false);

if ($queue_exists && $should_commit && $should_push) {

  // Define the job
  queue::define('commit_and_push_comment', function($job) {
    $uri = $job->get('uri');
    $commitMessage = "commented on " . $uri;

    include('git-commit-and-push-content/helpers.php');
    $gitHelper = new KirbyGitHelper();
    $gitHelper->kirbyChange($commitMessage);
  });

  // Queue job when hook gets invoked
  c::set('comments.hooks.did-save-comment', function ($comments, $comment, $commentPage) {
    queue::add('commit_and_push_comment', [
      'uri' => $comment->page()->uri()
    ]);
  });

}
```

Whenever I write a comment a job seems to be scheduled but with an error-message I don't really get because I have defined the job with the exact same name 🤔

<img width="464" alt="screen shot 2017-11-01 at 13 20 40" src="https://user-images.githubusercontent.com/3930150/32274562-ac988602-bf07-11e7-83d6-1e64ae1e88f9.png">

And even if I press the re-schedule button and execute the `worker.php` manually with `/usr/bin/php /[...]/site/plugins/queue-for-kirby/worker.php` nothing happens (nothing is committed nor pushed).

***

Second question: If I want to use a class of another Kirby plugin (like `KirbyGitHelper`) within the job is this the right way of doing it (with the `include` statement)? Or do I have to initialise some Kirby-things in advance?

Thanks in advance!
Dennis

**Comment by sebsel** [comment]
Hi Dennis! I've been busy, so late reply. 

Unfortunately, I can't reproduce this... but I also cannot get it working. I do not get the error-message you describe in my quick local setup. The queue finds the job-action and performs it. There are weird things happening inside that job-action, and debugging that part is not really what I want to do right now. 

I think the KirbyGitHelper (or the PHP Git library it uses) exits execution somewhere, instead of throwing an Exception. The queue worker tries to catch Exceptions, but it can't prolong execution if someone else terminates it. Well, that's the part I don't want to debug for you.

Still, since I get past the 'commit_and_push_comment' not defined, I think the problem does not lie with Queue for Kirby.

Silly question: are you sure you set **both** `gcapc-commit` and `gcapc-push` options to `true` in your config? If you don't, your hook and queue-action will not be defined, which will result in the message you describe.

***

Second question answered: you can just use `kirby()->plugin('plugin-name');` another time to make sure other plugins are loaded before this one. Behind the scenes this does an `include` for you, but it's better to leave it up to Kirby how they do it. Since you use the helpers.php, you might get away with the `include`, but I would still recommend `include_once`, since that one does not include it if it's already loaded :)

**Comment by sebsel** [comment]
I have made some changes to the plugin, so that it fails the job also when the job terminates the process. Hope that that's useful while debugging your Git problem :)

**Comment by wottpal** [comment]
Thanks for your help as always @sebsel. I really got it to work now and I'm super happy 🎉🙃

Just for reference I'll drop in my working solution. One of my faults was to assume that my server-configuration (i.e. `config.wottpal.com.php `) is applied when running the worker via the terminal which is not the case, of course! 🤦‍♂️

That's why I split my code into two pieces, in the first I set up the comments-hook in the configuration of my production-site (i.e. `config.wottpal.com.php`):

```php
/**
* If a comment was submitted add, commit & push it to the git-repo.
*/

c::set([
  'comments.hooks.did-save-comment' => function ($comments, $comment, $commentPage) {
    kirby()->plugin('queue-for-kirby');
    $queue_exists = class_exists('queue');
    $should_commit = c::get('gcapc-commit', false);
    $should_push = c::get('gcapc-push', false);

    if ($queue_exists && $should_commit && $should_push) {
      queue::add('commit_and_push_comment', [
        'uri' => $comment->page()->uri()
      ]);
    }
  }
]);
```

And the second piece is in the file `comments_queue.php` which I've stored under `sites/plugins`. I define my job there and unfortunately have to manually reconfigure the gcapc-plugin because like I've mentioned above my custom server-configuration isn't loaded at that point. Maybe I'll have a more flexible solution for this in the future but for now it works fine.

```php
<?php
/**
* Defines a queue job for asynchronously saving comments to version-control.
* Kirby Comments Plugin: https://github.com/Addpixel/KirbyComments
* Kirby Queue Plugin: https://github.com/sebsel/queue-for-kirby
*
* NOTE: Manually fire the worker with the following command.
* `sudo -u www-data /usr/bin/php /path/to/your/site/plugins/queue-for-kirby/worker.php`
*
* NOTE: To run the worker as a cronjob every 5-mins add the next line in `sudo crontab -e`
* `5 * * * * sudo -u www-data /usr/bin/php -q /path/to/your/site/plugins/queue-for-kirby/worker.php >/dev/null 2>&1`
*
*/


// Examine some conditions
kirby()->plugin('queue-for-kirby');
$queue_exists = class_exists('queue');

// Define the job if `queue` exists
if ($queue_exists) {
  queue::define('commit_and_push_comment', function($job) {

    // Manually re-configure `gcapc` because the cronjob doesn't know the actual server-address
    c::set([
      'gcapc-path' => kirby()->roots()->index(),
      'gcapc-branch' => 'master',
      'gcapc-pull' => true,
      'gcapc-push' => true,
      'gcapc-commit' => true
    ]);

    // Instantiate the `KirbyGitHelper`
    kirby()->plugin('git-commit-and-push-content');
    $gitHelper = new KirbyGitHelper();

    // Commit & Push the new comment asynchronously
    $uri = $job->get('uri');
    $commitMessage = "commented on " . $uri;
    $gitHelper->kirbyChange($commitMessage);

  });
}
```

In the comments of this file I've also described how to execute the worker and add all this as a cronjob. Everything works fine for me now :)

Thanks again,
Dennis

**Comment by sebsel** [comment]
Good to hear that you solved it! I've added a quick note to the readme, about the domain specific config. I did not think about that before, but now it seems logical. :)
