### ISSUE TITLE
Queue for Kirby + Kirby Autologin = true?

### ISSUE THREAD

**Issue by jenstornell** [sebsel/queue-for-kirby#4]
Hi there!

Maybe you can help me with this issue? I use REMOTE_ADDR to get the IP, but with your plugin it does not work. Maybe you know how I can get around it?

https://github.com/jenstornell/kirby-autologin/issues/4

The code is here: https://github.com/jenstornell/kirby-autologin/blob/master/kirby-autologin.php#L95

Thanks!

**Comment by sebsel** [comment]
I don't think it's something I can fix in my code, so I'll reply over there :)
